package uz.hamkorbank.commhub.application.service.support;

import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.stereotype.Component;
import uz.hamkorbank.commhub.application.mapper.ProviderSubmissionMapper;
import uz.hamkorbank.commhub.application.port.out.ClockPort;
import uz.hamkorbank.commhub.application.port.out.provider.EmailProviderPort;
import uz.hamkorbank.commhub.application.port.out.provider.ProviderAck;
import uz.hamkorbank.commhub.application.port.out.provider.ProviderPort;
import uz.hamkorbank.commhub.application.port.out.provider.ProviderTemplateBinding;
import uz.hamkorbank.commhub.application.port.out.provider.PushProviderPort;
import uz.hamkorbank.commhub.application.port.out.provider.SmsProviderPort;
import uz.hamkorbank.commhub.domain.model.Message;
import uz.hamkorbank.commhub.domain.model.type.Channel;
import uz.hamkorbank.commhub.domain.model.type.ErrorClass;
import uz.hamkorbank.commhub.domain.model.vo.ProviderMessageId;
import uz.hamkorbank.commhub.domain.model.vo.ProviderRef;
import uz.hamkorbank.commhub.domain.model.vo.PushToken;
import uz.hamkorbank.commhub.domain.support.Guard;

/**
 * Resolves the adapter of a routed provider and hands the message over (MP-05, AR-04, AD-04).
 *
 * <p>This is the single place where a {@code ProviderRef} produced by the {@code Router} becomes a
 * concrete integration: the adapter whose {@code adapterType} matches. Adapters are discovered
 * through the container, so a new provider is a new bean and nothing else (AR-04).
 *
 * <p>Adapter failures never escape as exceptions: an unexpected error becomes a retryable
 * {@link ProviderAck}, so the sending saga keeps its single decision path (PR-01).
 */
@Component
public class ProviderGateway {

    private static final String UNEXPECTED_ERROR_CODE = "ADAPTER_ERROR";

    private final ObjectProvider<SmsProviderPort> smsPorts;
    private final ObjectProvider<EmailProviderPort> emailPorts;
    private final ObjectProvider<PushProviderPort> pushPorts;
    private final ProviderSubmissionMapper mapper;
    private final ProviderMessageIdFactory providerMessageIds;
    private final ClockPort clock;

    public ProviderGateway(
            ObjectProvider<SmsProviderPort> smsPorts,
            ObjectProvider<EmailProviderPort> emailPorts,
            ObjectProvider<PushProviderPort> pushPorts,
            ProviderSubmissionMapper mapper,
            ProviderMessageIdFactory providerMessageIds,
            ClockPort clock) {
        this.smsPorts = Guard.notNull(smsPorts, "smsPorts");
        this.emailPorts = Guard.notNull(emailPorts, "emailPorts");
        this.pushPorts = Guard.notNull(pushPorts, "pushPorts");
        this.mapper = Guard.notNull(mapper, "mapper");
        this.providerMessageIds = Guard.notNull(providerMessageIds, "providerMessageIds");
        this.clock = Guard.notNull(clock, "clock");
    }

    /** Whether an adapter is deployed for the routed provider. */
    public boolean supports(ProviderRef provider) {
        return provider != null && adapterExists(provider);
    }

    /**
     * Identifier the Hub assigns to the message on the provider side; providers that assign their own
     * ignore it (§9.1, §9.2).
     */
    public ProviderMessageId providerMessageIdFor(Message message) {
        return providerMessageIds.create(null, message.id());
    }

    /**
     * Submits the message to its routed provider.
     *
     * @param providerMessageId id generated by the Hub for this attempt (§9.1)
     * @param binding provider-side template to use instead of the text; {@code null} when not mapped
     */
    public ProviderAck submit(
            Message message,
            ProviderRef provider,
            ProviderMessageId providerMessageId,
            ProviderTemplateBinding binding) {
        Guard.notNull(message, "message");
        Guard.notNull(provider, "provider");
        try {
            return switch (provider.channel()) {
                case SMS -> submitSms(message, provider, providerMessageId, binding);
                case EMAIL -> submitEmail(message, provider);
                case PUSH -> submitPush(message, provider);
            };
        } catch (RuntimeException e) {
            return ProviderAck.failed(
                    UNEXPECTED_ERROR_CODE,
                    ErrorClass.RETRYABLE,
                    "%s: %s".formatted(e.getClass().getSimpleName(), e.getMessage()),
                    clock.now());
        }
    }

    private ProviderAck submitSms(
            Message message,
            ProviderRef provider,
            ProviderMessageId providerMessageId,
            ProviderTemplateBinding binding) {
        return port(smsPorts, provider)
                .map(adapter -> adapter.submit(mapper.toSmsSubmission(message, provider, providerMessageId, binding)))
                .orElseGet(() -> noAdapter(provider));
    }

    private ProviderAck submitEmail(Message message, ProviderRef provider) {
        return port(emailPorts, provider)
                .map(adapter -> adapter.submit(mapper.toEmailSubmission(message, provider)))
                .orElseGet(() -> noAdapter(provider));
    }

    /**
     * Submits the push to the first device token the adapter serves.
     *
     * <p>Fan-out over every active device of a recipient arrives with the push stage (PU-09, PU-10);
     * the contract of the port is already per token, so that change stays inside the saga.
     */
    private ProviderAck submitPush(Message message, ProviderRef provider) {
        Optional<PushProviderPort> adapter = port(pushPorts, provider);
        if (adapter.isEmpty()) {
            return noAdapter(provider);
        }
        List<PushToken> tokens = message.recipient().pushTokens().stream()
                .filter(token -> adapter.get().supportsPlatform(token.platform()))
                .toList();
        if (tokens.isEmpty()) {
            return ProviderAck.rejected(
                    UNEXPECTED_ERROR_CODE,
                    "recipient has no device token for adapter "
                            + provider.adapterType().value(),
                    clock.now());
        }
        return adapter.get().submit(mapper.toPushSubmission(message, provider, tokens.getFirst()));
    }

    private <T extends ProviderPort> Optional<T> port(ObjectProvider<T> ports, ProviderRef provider) {
        return ports.stream().filter(port -> port.supports(provider)).findFirst();
    }

    private boolean adapterExists(ProviderRef provider) {
        ObjectProvider<? extends ProviderPort> ports =
                switch (provider.channel()) {
                    case SMS -> smsPorts;
                    case EMAIL -> emailPorts;
                    case PUSH -> pushPorts;
                };
        return ports.stream().anyMatch(port -> port.supports(provider));
    }

    private ProviderAck noAdapter(ProviderRef provider) {
        return ProviderAck.failed(
                UNEXPECTED_ERROR_CODE,
                ErrorClass.NON_RETRYABLE,
                "no adapter deployed for provider %s (%s)"
                        .formatted(
                                provider.code().value(), provider.adapterType().value()),
                clock.now());
    }

    /** Channel of a routed provider; kept for readability at the call sites. */
    public static Channel channelOf(ProviderRef provider) {
        return Guard.notNull(provider, "provider").channel();
    }
}
